---
name: Publish docs via GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install mkdocs and material theme
        run: pip install mkdocs-material

      - name: Copy changelog and license into docs/
        run: |
          cp LICENSE docs/license.md
          cp CHANGELOG.md docs/changelog.md

      - name: Deploy website
        run: mkdocs gh-deploy --force
